#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import argparse, html, json, os, shutil
from aipf.config import corpus_path, internal_gallery_path
try:
    from PIL import Image
except Exception:
    Image=None


def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--corpus-root', help='Corpus root. Defaults to AIPF_CORPUS_PATH.'); ap.add_argument('--manifest',default='corpus/indexes/image_library_manifest.json'); ap.add_argument('--prompts',default='corpus/indexes/prompt_index.json'); ap.add_argument('--output', help='Gallery output directory. Defaults to AIPF_INTERNAL_GALLERY_PATH.'); ap.add_argument('--thumbnails',action='store_true'); args=ap.parse_args()
    repo=Path(__file__).resolve().parents[1];
    root = (
        Path(args.corpus_root).expanduser().resolve()
        if args.corpus_root
        else corpus_path()
    )

    out = (
        Path(args.output).expanduser().resolve()
        if args.output
        else internal_gallery_path()
    )

    if root is None:
        ap.error(
            '--corpus-root or AIPF_CORPUS_PATH is required'
        )

    if out is None:
        ap.error(
            '--output or AIPF_INTERNAL_GALLERY_PATH is required'
        )

    if not root.exists():
        ap.error(f'corpus root does not exist: {root}')

    out.mkdir(parents=True, exist_ok=True)
    manifest=json.loads((repo/args.manifest).read_text(encoding='utf-8')); prompts={p['prompt_id']:p for p in json.loads((repo/args.prompts).read_text(encoding='utf-8'))['prompt_records']}
    thumbdir=out/'thumbs'; thumbdir.mkdir(exist_ok=True)
    rows=[]
    for i,a in enumerate(manifest['assets']):
        src=root/a['relative_path']
        image_uri=src.as_uri() if src.exists() else ''
        thumb_uri=image_uri
        if args.thumbnails and Image and src.exists():
            tp=thumbdir/(a['asset_id']+'.jpg')
            if not tp.exists():
                try:
                    im=Image.open(src); im.thumbnail((320,320)); im.convert('RGB').save(tp,quality=72,optimize=True)
                except Exception: pass
            if tp.exists(): thumb_uri=tp.relative_to(out).as_posix()
        p=prompts.get(a.get('associated_prompt_id'))
        prompt=(p or {}).get('prompt_text','')
        methods=', '.join((p or {}).get('decomposition',{}).get('prompt_methods',[]))
        rows.append(f'''<article class="card" data-collection="{html.escape(a['source_collection'])}" data-tags="{html.escape(' '.join(a.get('tags',[])))}"><a href="{html.escape(image_uri)}"><img loading="lazy" src="{html.escape(thumb_uri)}"></a><div class="meta"><b>{html.escape(a['relative_path'].split('/')[-1])}</b><span>{html.escape(a['source_collection'])} · {html.escape(a.get('creator') or 'creator not normalized')}</span><span>prompt: {html.escape(a.get('prompt_association_confidence','unknown'))}</span><span>methods: {html.escape(methods or 'unknown')}</span></div><details><summary>Prompt / decomposition</summary><pre>{html.escape(prompt or 'No associated prompt extracted with sufficient confidence.')}</pre></details></article>''')
    options=''.join(f'<option>{c}</option>' for c in sorted({a['source_collection'] for a in manifest['assets']}))
    page=f'''<!doctype html><meta charset="utf-8"><title>AIPF V3.2 Internal Prompt Gallery</title><style>body{{font:14px system-ui;margin:20px;background:#111;color:#eee}}header{{position:sticky;top:0;background:#111;padding:8px;z-index:2}}input,select{{padding:8px;margin-right:8px}}.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:14px}}.card{{background:#1d1d1d;padding:10px;border-radius:12px}}img{{width:100%;height:260px;object-fit:contain;background:#000}}.meta{{display:grid;gap:4px;margin:8px 0;color:#ccc}}pre{{white-space:pre-wrap;max-height:400px;overflow:auto;background:#0d0d0d;padding:10px}}</style><header><h1>AI Image Prompt Factory V3.2 · Internal Research Gallery</h1><p>Internal source corpus. Not the public benchmark gallery.</p><select id="c"><option value="">All collections</option>{options}</select><input id="q" placeholder="Search filename/tags/prompt" size="38"><span id="n"></span></header><main class="grid">{''.join(rows)}</main><script>const cards=[...document.querySelectorAll('.card')],c=document.querySelector('#c'),q=document.querySelector('#q'),n=document.querySelector('#n');function f(){{let x=q.value.toLowerCase(),col=c.value;let k=0;cards.forEach(e=>{{let ok=(!col||e.dataset.collection===col)&&(!x||e.innerText.toLowerCase().includes(x)||e.dataset.tags.includes(x));e.style.display=ok?'':'none';if(ok)k++}});n.textContent=k+' / '+cards.length}}c.onchange=q.oninput=f;f()</script>'''
    (out/'index.html').write_text(page,encoding='utf-8')
    (out/'README.txt').write_text('Internal research gallery generated by AI Image Prompt Factory V3.2. Re-run generator when AIPF_CORPUS_PATH changes.\n')
    print(json.dumps({'assets':len(rows),'output':str(out/'index.html'),'thumbnails':args.thumbnails},indent=2))
if __name__=='__main__': main()
